### ISSUE TITLE
The Liftbridge subscriber client is not working with the replicacount >1

### ISSUE THREAD

**Issue by akshay071990** [pozetroninc/liftbridge-helm-chart#3]
HI Neil and Hazim,

Thanks for developing the helmchart for the Liftbridge!

Facing one issue, when i installed the chart with the default values(replica count = 3) as it is.. i found that my Liftbridge subscriber code (using: https://github.com/liftbridge-io/java-liftbridge) is throwing the below error (seems like the request is getting forwarded to the **follower** server not the **Leader** server!):

`Exception in thread "main" io.grpc.StatusRuntimeException: FAILED_PRECONDITION: **Server not partition leader**
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:449)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:521)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)`

But this works perfectly fine when the replica count is set to 1 (as there will be no followers), So is this a bug or some other configurations are required?
Can u pls helm me to resolve this..
Thanks
Akshay

**Comment by tylertreat** [comment]
This is an issue with the Java client as it does not yet implement metadata lookup in order to make requests to the appropriate node in the cluster.

**Comment by akshay071990** [comment]
Hi Tyler,


Oh Ok so do we have any workaround for this to listen this to a leader server or  till this is implemented i need to use **golang client**? 
But i have raised another issue with **golang client** its not listening to port other than 9292 "**https://github.com/liftbridge-io/go-liftbridge/issues/65**". So basically nodeport is a blocker.

My primary use case is to deploy Liftbridge and NATS (Replacement for Kafka) on a single node K8s cluster as a microservice and will have multiple Microservices publishing and subscribing to the respective streams.

Pls provide your suggestions!

Thanks
AKshay

**Comment by tylertreat** [comment]
The only workaround is to use a single-node cluster or use the Go client until the Java client is finished. It's next on my list to do.

**Comment by neil-pozetroninc** [comment]
@akshay071990, since @tylertreat has answered your questions I'm going to close out this issue. Thanks @tylertreat!
